import type { OfficialSource } from "@/lib/ingestion/types";

export const officialSourceRegistry: OfficialSource[] = [
  {
    id: "cnpq-chamadas",
    name: "CNPq — Chamadas Públicas",
    institutionName: "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    institutionAcronym: "CNPq",
    sourceType: "federal_government",
    baseUrl: "https://www.gov.br/cnpq/",
    allowedDomains: ["www.gov.br"],
    allowedPathPrefixes: ["/cnpq/"],
    listingUrls: [
      "https://www.gov.br/cnpq/pt-br/chamadas",
      "https://www.gov.br/cnpq/pt-br/chamadas/todas-as-chamadas",
      "https://www.gov.br/cnpq/pt-br/chamadas/resultados-publicados",
    ],
    extractionMode: "manual_assisted",
    audienceScope: ["mixed"],
    geographicScope: ["Brasil"],
    categories: ["pesquisa", "chamadas nacionais"],
    priority: 80,
    active: true,
    notes: "Chamadas institucionais não podem ser apresentadas como candidatura direta.",
  },
  {
    id: "cnpq-programas-ict",
    name: "CNPq — Programas de Iniciação Científica e Tecnológica",
    institutionName: "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
    institutionAcronym: "CNPq",
    sourceType: "official_reference",
    baseUrl: "https://www.gov.br/cnpq/",
    allowedDomains: ["www.gov.br"],
    allowedPathPrefixes: ["/cnpq/"],
    listingUrls: ["https://www.gov.br/cnpq/pt-br/acesso-a-informacao/acoes-e-programas/programas/programas-ict"],
    extractionMode: "reference_only",
    audienceScope: ["undergraduate_student", "high_school_student"],
    geographicScope: ["Brasil"],
    categories: ["PIBIC", "PIBITI", "PIBIC-Af", "PIBIC-EM"],
    priority: 60,
    active: true,
    notes: "Referência de programa; nunca gera oportunidade automaticamente.",
  },
  {
    id: "capes-bolsas",
    name: "CAPES — Bolsas e Programas",
    institutionName: "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior",
    institutionAcronym: "CAPES",
    sourceType: "federal_government",
    baseUrl: "https://www.gov.br/capes/",
    allowedDomains: ["www.gov.br"],
    allowedPathPrefixes: ["/capes/"],
    listingUrls: [
      "https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/bolsas",
      "https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/bolsas/bolsas-e-auxilios-internacionais",
    ],
    extractionMode: "manual_assisted",
    audienceScope: ["mixed"],
    geographicScope: ["Brasil", "Internacional"],
    categories: ["bolsas", "mobilidade", "pós-graduação"],
    priority: 80,
    active: true,
    notes: "O nível acadêmico deve ser identificado explicitamente.",
  },
  {
    id: "ufsc-propesq",
    name: "UFSC — Pró-Reitoria de Pesquisa",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://propesq.ufsc.br/",
    allowedDomains: ["propesq.ufsc.br", "pop.propesq.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://propesq.ufsc.br/", "https://propesq.ufsc.br/category/noticias/", "https://pop.propesq.ufsc.br/"],
    extractionMode: "rss",
    audienceScope: ["undergraduate_student", "postgraduate_student"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["PIBIC", "PIBITI", "PIBIC-Af", "BIPI", "pesquisa"],
    priority: 100,
    active: true,
    notes: "Editais de orientadores usam application_via_professor.",
  },
  {
    id: "ufsc-proex",
    name: "UFSC — Pró-Reitoria de Extensão",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://proex.ufsc.br/",
    allowedDomains: ["proex.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://proex.ufsc.br/"],
    extractionMode: "rss",
    audienceScope: ["undergraduate_student", "postgraduate_student"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["PROBOLSAS", "PROAA", "extensão"],
    priority: 100,
    active: true,
  },
  {
    id: "ufsc-prae",
    name: "UFSC — Permanência e Assuntos Estudantis",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://prae.ufsc.br/",
    allowedDomains: ["prae.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://prae.ufsc.br/", "https://prae.ufsc.br/editais-por-programa/editais-bolsa-estudantil/"],
    extractionMode: "rss",
    audienceScope: ["undergraduate_student", "postgraduate_student"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["assistência estudantil", "permanência", "moradia"],
    priority: 100,
    active: true,
  },
  {
    id: "ufsc-prograd",
    name: "UFSC — Graduação e Monitoria",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://prograd.ufsc.br/",
    allowedDomains: ["prograd.ufsc.br", "pmiq.prograd.ufsc.br", "caap.prograd.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://prograd.ufsc.br/", "https://pmiq.prograd.ufsc.br/editais/", "https://caap.prograd.ufsc.br/"],
    extractionMode: "rss",
    audienceScope: ["undergraduate_student"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["monitoria", "apoio pedagógico", "graduação"],
    priority: 95,
    active: true,
  },
  {
    id: "ufsc-sinova",
    name: "UFSC — SINOVA",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://sinova.ufsc.br/",
    allowedDomains: ["sinova.ufsc.br", "propesq.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://sinova.ufsc.br/editais-andamento/"],
    extractionMode: "html",
    audienceScope: ["mixed"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["inovação", "empreendedorismo", "incubação"],
    priority: 85,
    active: true,
  },
  {
    id: "ufsc-sinter",
    name: "UFSC — Secretaria de Relações Internacionais",
    institutionName: "Universidade Federal de Santa Catarina",
    institutionAcronym: "UFSC",
    sourceType: "federal_university",
    baseUrl: "https://sinter.ufsc.br/",
    allowedDomains: ["sinter.ufsc.br", "arquivos.ufsc.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: ["https://sinter.ufsc.br/"],
    extractionMode: "rss",
    audienceScope: ["undergraduate_student", "postgraduate_student"],
    geographicScope: ["Santa Catarina", "Internacional"],
    categories: ["intercâmbio", "mobilidade", "PEC-G"],
    priority: 95,
    active: true,
  },
  {
    id: "fapesc-chamadas",
    name: "FAPESC — Chamadas",
    institutionName: "Fundação de Amparo à Pesquisa e Inovação de Santa Catarina",
    institutionAcronym: "FAPESC",
    sourceType: "government_foundation",
    baseUrl: "https://fapesc.sc.gov.br/",
    allowedDomains: ["fapesc.sc.gov.br", "sig.fapesc.sc.gov.br"],
    allowedPathPrefixes: ["/"],
    listingUrls: [
      "https://fapesc.sc.gov.br/chamadas-abertas/",
      "https://fapesc.sc.gov.br/chamadas-em-andamento/",
      "https://fapesc.sc.gov.br/divulgacao-dos-resultados/",
      "https://fapesc.sc.gov.br/chamadas-encerradas/",
    ],
    extractionMode: "html",
    audienceScope: ["mixed"],
    geographicScope: ["Santa Catarina"],
    location: { stateCode: "SC", cityName: null },
    categories: ["pesquisa", "inovação", "bolsas"],
    priority: 90,
    active: true,
    notes: "Publicar para estudantes apenas quando houver participação direta ou seleção específica.",
  },
];

export function getOfficialSource(id: string) {
  return officialSourceRegistry.find((source) => source.id === id);
}
